# Use the README file as a reference to customize settings.

AdminUser:
  fields:
    default: first_name, last_name, email, crypted_password
    form: first_name, last_name, email, crypted_password
  relationships: 
  application: Application
