# Use the README file as a reference to customize settings.

Advert:
  fields:
    default: user_id, uid, make_model, price, contact_number, secondary_number, email, basics_saved, details_saved, features_saved, photos_saved, contact_saved, activated, sold, status, delete_reason_id
    form: user_id, uid, make_model, price, contact_number, secondary_number, email, popularity, basics_saved, details_saved, features_saved, photos_saved, contact_saved, activated, sold, status, delete_reason_id
  relationships: vehicle, order
  application: Application
