# Use the README file as a reference to customize settings.

Bodytype:
  fields:
    default: name, popularity
    form: name, popularity
  relationships: translations, vehicles
  application: Application
