# Use the README file as a reference to customize settings.

DealerPicture:
  fields:
    default: user_id, name, file, remote_file_url
    form: user_id, name, file, remote_file_url
  relationships: 
  application: Application
