# Use the README file as a reference to customize settings.

SearchAlert:
  fields:
    default: search_id, user_id, results
    form: search_id, user_id, results
  relationships: 
  application: Application
