# Use the README file as a reference to customize settings.

Type:
  fields:
    default: name, path_name
    form: name, path_name
  relationships: vehicles, adverts, bodytypes, makes
  application: Application
