defaults: &defaults
  host: 127.0.0.1
  port: 6379
  password: maricavorredis001
  
development:
  <<: *defaults 
  #password:  #use for localhost, remove for deployment

staging:
  <<: *defaults

production:
  <<: *defaults
  


